export interface Coordinates {
  latitude: number;
  longitude: number;
  accuracy: number;
  heading: number | null;
  speed: number | null;
}

export interface User {
  id: string;
  name: string;
  avatar: string;
  location: Coordinates | null;
  lastUpdated: Date;
  isSelf: boolean;
}

export interface Friend extends User {
  statusMessage: string; // Generated by AI
  isTracking: boolean;
}

export enum AppState {
  AUTH = 'AUTH',
  DASHBOARD = 'DASHBOARD',
}